<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I understand that gift certificates a_cdd828</name>
   <tag></tag>
   <elementGuidId>0ceee2ba-9ccc-4486-945a-365c269a58b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='agree']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;agree&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d729f7c-d856-4d28-a239-081aa971dbac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1b664837-ceb9-41d8-bcd7-a2cbd72e77eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agree</value>
      <webElementGuid>d6ad0a15-92b2-45e2-b7ec-bc9f0ad28c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>14123397-bb30-49e4-9105-a9e0d0387a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;buttons clearfix&quot;]/div[@class=&quot;pull-right&quot;]/input[1]</value>
      <webElementGuid>de049041-870e-42a5-b959-00cc804f9315</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='agree']</value>
      <webElementGuid>12e75301-d227-4633-ba14-ca49d6d06fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/form/div[8]/div/input</value>
      <webElementGuid>7ba31af5-3222-45ee-86cb-72a280733edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>c7fc0f9e-67dd-4f1f-a3c9-faf976350653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'agree']</value>
      <webElementGuid>6f4812a2-b940-4136-b4a1-e66c54f7a3fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
