<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Recurring payments</name>
   <tag></tag>
   <elementGuidId>44bad2d2-b6cc-4183-bbb2-75635f719f8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/ul[2]/li[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b18371ac-de25-4b76-8ddd-eaf138f30b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://tutorialsninja.com/demo/index.php?route=account/recurring</value>
      <webElementGuid>6329fe71-64ef-4af5-a2a6-fba2b731bdab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recurring payments</value>
      <webElementGuid>874a9688-814f-463a-af1e-18acabfe1565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/ul[@class=&quot;list-unstyled&quot;]/li[6]/a[1]</value>
      <webElementGuid>cea0b1c0-4c17-4722-b14f-d1b529984a4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/ul[2]/li[6]/a</value>
      <webElementGuid>17fecaf2-9de6-45d3-91d1-b4be47e30b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Recurring payments')]</value>
      <webElementGuid>9c05233a-59b4-479e-a50b-1387836bf032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Transactions'])[1]/following::a[1]</value>
      <webElementGuid>765cefd9-dcbd-430d-9ee8-e755f3c3243b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View your return requests'])[1]/following::a[2]</value>
      <webElementGuid>de2905a5-fa11-415d-afcb-cc3f8ebc6f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Affiliate Account'])[1]/preceding::a[1]</value>
      <webElementGuid>c2dbc093-a414-401c-b5a6-3efcd48f6244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register for an affiliate account'])[1]/preceding::a[1]</value>
      <webElementGuid>c5a6410d-9067-45ff-8363-11e6b3962ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recurring payments']/parent::*</value>
      <webElementGuid>26b59fef-812a-4d2b-ac44-68130d7885fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://tutorialsninja.com/demo/index.php?route=account/recurring']</value>
      <webElementGuid>d0cacd39-4178-4f28-bb8b-6f3903958948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[6]/a</value>
      <webElementGuid>7b8b9784-148c-4835-9b57-3dddc1be38fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://tutorialsninja.com/demo/index.php?route=account/recurring' and (text() = 'Recurring payments' or . = 'Recurring payments')]</value>
      <webElementGuid>7b0c704c-7a35-4f9f-82bc-0960f1724c03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
