<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change your password</name>
   <tag></tag>
   <elementGuidId>3cb50495-62c0-406d-a522-85a388211874</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0fb39054-ebb2-45a7-bb77-af5c0e146f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://tutorialsninja.com/demo/index.php?route=account/password</value>
      <webElementGuid>cf049605-bb60-4ce5-bd50-6c7adf99e295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change your password</value>
      <webElementGuid>29853bfe-acc6-4a70-96ef-3dec1b6aca57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/ul[@class=&quot;list-unstyled&quot;]/li[2]/a[1]</value>
      <webElementGuid>950862fb-955f-4acd-ae56-1091e34ad608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/ul/li[2]/a</value>
      <webElementGuid>18e80dd7-8166-4f05-9664-316ed0261fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Change your password')]</value>
      <webElementGuid>fee6b58c-d8c1-4d90-a7d9-1386c55df08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit your account information'])[1]/following::a[1]</value>
      <webElementGuid>062fad4c-d416-4ce3-9749-3d65ebf63b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[4]/following::a[2]</value>
      <webElementGuid>6b7f87d4-98d6-4caf-b581-ad82d5e49055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modify your address book entries'])[1]/preceding::a[1]</value>
      <webElementGuid>d3fd8750-735f-442c-a0ab-2c4e6a5c9bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modify your wish list'])[1]/preceding::a[2]</value>
      <webElementGuid>5c97fcd4-eb2c-4eed-98f0-3b68950299b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Change your password']/parent::*</value>
      <webElementGuid>bc085d97-0301-4388-ba7b-3db9586fa9b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://tutorialsninja.com/demo/index.php?route=account/password']</value>
      <webElementGuid>10d9310f-edad-40b3-9005-4c48fc4c6204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[2]/a</value>
      <webElementGuid>99168528-ef1a-48db-bee5-6342ea5a36c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://tutorialsninja.com/demo/index.php?route=account/password' and (text() = 'Change your password' or . = 'Change your password')]</value>
      <webElementGuid>ea4be91a-1466-4ec2-9ffc-e43a47cf9525</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
