<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Number_bank_account_number</name>
   <tag></tag>
   <elementGuidId>8cb0252c-ffbb-4df1-b41d-b54a9b6848aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-bank-account-number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-bank-account-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>efdf2c86-cbf1-4f08-947d-9ed5f6a9a0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5747f362-9f20-46c9-8b4c-31350bb2224f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bank_account_number</value>
      <webElementGuid>0b0c3a10-1f49-4000-aad2-11d992ed485d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Account Number</value>
      <webElementGuid>79d9d24c-dfae-4707-969c-601427dc8099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-bank-account-number</value>
      <webElementGuid>e4f713fb-63fa-463a-bc1c-1db5dff3f0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>49edc9b4-afd7-4de9-8705-d5379cc1f8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-bank-account-number&quot;)</value>
      <webElementGuid>c86798ee-52d6-4025-b851-42757c168696</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-bank-account-number']</value>
      <webElementGuid>729e061a-9f30-4750-9d2e-68390e6136a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-bank']/div[5]/div/input</value>
      <webElementGuid>4d3f27ce-d2b5-4441-a067-6b3c07444a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>95b8b68b-c3c9-4881-8fdc-fe18fc5a2481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bank_account_number' and @placeholder = 'Account Number' and @id = 'input-bank-account-number']</value>
      <webElementGuid>11c4ea30-8312-49e8-b24f-d72cef59ece1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
