<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ABABSB number (Branch Number)_bank_br_618171</name>
   <tag></tag>
   <elementGuidId>eb6883c8-8fa5-4ffb-b0a4-e950b311261c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-bank-branch-number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-bank-branch-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92cfa73a-777a-4c67-86d6-f6ba10e48206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6810bee-dede-4185-9030-d3a9357c8c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bank_branch_number</value>
      <webElementGuid>3410fcc4-715d-4dab-8ef8-e8f6c9278212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ABA/BSB number (Branch Number)</value>
      <webElementGuid>53b0fc80-cf7a-4b81-ac4b-8a887a490c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-bank-branch-number</value>
      <webElementGuid>6b5a0619-7718-411d-8488-1835a391a786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>10446aee-fcf0-4333-9ea9-6545b311f342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-bank-branch-number&quot;)</value>
      <webElementGuid>7b14e34f-db63-4458-8e8a-02bf9ba51b21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-bank-branch-number']</value>
      <webElementGuid>d741f9cb-5379-4acd-8d07-b016ae4356ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-bank']/div[2]/div/input</value>
      <webElementGuid>e848584c-4100-4685-831b-3d2c7057c2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>016012a7-5334-4553-8243-42302e9367cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bank_branch_number' and @placeholder = 'ABA/BSB number (Branch Number)' and @id = 'input-bank-branch-number']</value>
      <webElementGuid>ab3fc210-30bb-4402-b42f-3619f3f05209</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
