<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SWIFT Code_bank_swift_code</name>
   <tag></tag>
   <elementGuidId>636b4641-0c24-41a9-83d5-638391752f86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-bank-swift-code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-bank-swift-code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a49e5d6-c18e-49b0-9695-f5188ac1dedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7a88e40-eee4-48ac-9f07-66f40c892f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bank_swift_code</value>
      <webElementGuid>52e80ae2-9810-4035-b396-6fac162010a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>SWIFT Code</value>
      <webElementGuid>3b14175f-9f59-43bb-b097-4a9a5b1041cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-bank-swift-code</value>
      <webElementGuid>1c4eff83-b283-491d-82fe-b6b6a699bdb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>22a24851-a341-4e61-91e7-a29d26a3783c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-bank-swift-code&quot;)</value>
      <webElementGuid>727624b6-f1c1-4d3f-9139-3e8ba7dcb11f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-bank-swift-code']</value>
      <webElementGuid>b21e24d7-356b-4006-94de-baeb2c676bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-bank']/div[3]/div/input</value>
      <webElementGuid>314c3b94-8569-4ce9-86eb-8e17127f2b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/input</value>
      <webElementGuid>e5436632-c058-47c3-8665-b8c615238493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bank_swift_code' and @placeholder = 'SWIFT Code' and @id = 'input-bank-swift-code']</value>
      <webElementGuid>f481498b-c0e8-4ace-9e9b-97f567af8836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
