<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank Name_bank_name</name>
   <tag></tag>
   <elementGuidId>d07ba881-a1bb-4151-8fe5-148e2d2a31b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-bank-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-bank-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61121b8b-9772-42b1-b19c-ef5d5872d3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0545d2a1-4c9b-4ee7-8a19-be0532e96aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bank_name</value>
      <webElementGuid>699bd326-f841-4f98-b57a-baedda523997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bank Name</value>
      <webElementGuid>c8c1bb7d-2806-4a9f-85d2-1b4aad6e4995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-bank-name</value>
      <webElementGuid>cab3d992-bfaa-41c9-ae43-c2a0612c23dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1c4e2552-92ce-4fdf-b164-240ff414b753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-bank-name&quot;)</value>
      <webElementGuid>e46dd53c-a0ee-4219-a887-082a6ead78df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-bank-name']</value>
      <webElementGuid>d56cf099-f8e1-48a3-87c1-dd78994fe100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-bank']/div/div/input</value>
      <webElementGuid>6f3ef5f4-bdbf-4907-b242-dc2496054574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>95ae9e06-fcfa-4223-b081-a9fbacd3d4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bank_name' and @placeholder = 'Bank Name' and @id = 'input-bank-name']</value>
      <webElementGuid>8baf4515-7ac9-4c01-b7f8-66359e951973</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
