<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--- Please Select --- BarisalChittag_f13a22</name>
   <tag></tag>
   <elementGuidId>dc6ebaf9-d5a0-4de6-8f77-593f37e72f8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='input-zone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-zone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b861a41c-01da-40b1-b6a2-bc90d1c4aa0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zone_id</value>
      <webElementGuid>27d7bc64-6f53-4a7b-bed4-f3cc63f77eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-zone</value>
      <webElementGuid>54286347-b3a3-4ad4-a938-186aa8fadc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>efce5bcf-2c86-4646-809f-73aeaf7f43b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --- Please Select --- BarisalChittagongDhakaKhulnaRajshahiSylhet</value>
      <webElementGuid>c0155725-671e-4b65-ac25-3a00d8bfe184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-zone&quot;)</value>
      <webElementGuid>be215952-1852-4656-a613-fb87444c044b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='input-zone']</value>
      <webElementGuid>50812942-9356-443b-a3b2-1376c41b48ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/form/fieldset/div[9]/div/select</value>
      <webElementGuid>44549e92-f9b9-4fd5-b68b-27fa596309f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region / State'])[1]/following::select[1]</value>
      <webElementGuid>714369fe-e676-4787-8cdc-6547bc56e8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[2]</value>
      <webElementGuid>4fdd293d-ee59-433a-bb66-37de5e4972ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Address'])[1]/preceding::select[1]</value>
      <webElementGuid>6d7ac38a-c3bc-4d11-8d39-f289d997627e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/select</value>
      <webElementGuid>194fd194-512e-4036-8350-f292f08366e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'zone_id' and @id = 'input-zone' and (text() = ' --- Please Select --- BarisalChittagongDhakaKhulnaRajshahiSylhet' or . = ' --- Please Select --- BarisalChittagongDhakaKhulnaRajshahiSylhet')]</value>
      <webElementGuid>fb196feb-efa2-46cc-a0ff-89ffe37cb38c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
